import type { Folder } from '@/types/folder';

export const mockFolders: Folder[] = [
  {
    id: '1',
    name: 'My Business Ideas',
    description: 'Startup concepts and plans',
    color: '#E3F2FD',
    icon: '💡',
    is_pinned: true,
    user_id: '1',
    created_at: '2025-11-14',
    updated_at: '2025-11-14',
  },
  {
    id: '2',
    name: 'Uncategorized',
    description: 'General notes',
    color: '#F3E5F5',
    icon: '📁',
    is_pinned: false,
    user_id: '1',
    created_at: '2025-11-14',
    updated_at: '2025-11-14',
  },
  {
    id: '3',
    name: 'Data Mining',
    description: 'Course notes and assignments',
    color: '#E1F5FE',
    icon: '📊',
    is_pinned: false,
    user_id: '1',
    created_at: '2025-11-14',
    updated_at: '2025-11-14',
  },
  {
    id: '4',
    name: 'Coffee Roastery with PLC',
    description: 'IoT project documentation',
    color: '#FFF3E0',
    icon: '☕',
    is_pinned: false,
    user_id: '1',
    created_at: '2025-11-14',
    updated_at: '2025-11-14',
  },
  {
    id: '5',
    name: 'Web Development',
    description: 'Frontend and backend tutorials',
    color: '#E8F5E9',
    icon: '💻',
    is_pinned: true,
    user_id: '1',
    created_at: '2025-11-10',
    updated_at: '2025-11-10',
  },
  {
    id: '6',
    name: 'Machine Learning',
    description: 'AI and ML algorithms',
    color: '#FCE4EC',
    icon: '🤖',
    is_pinned: false,
    user_id: '1',
    created_at: '2025-11-08',
    updated_at: '2025-11-08',
  },
  {
    id: '7',
    name: 'Travel Plans 2026',
    description: 'Itineraries and bookings',
    color: '#FFF9C4',
    icon: '✈️',
    is_pinned: false,
    user_id: '1',
    created_at: '2025-11-05',
    updated_at: '2025-11-05',
  },
  {
    id: '8',
    name: 'Recipe Collection',
    description: 'Favorite recipes',
    color: '#FFEBEE',
    icon: '🍳',
    is_pinned: true,
    user_id: '1',
    created_at: '2025-11-01',
    updated_at: '2025-11-01',
  },
];

export const mockUser = {
  id: '1',
  name: 'Ghazy Urbayani',
  email: 'ghazy@gathernote.com',
  avatar_url: 'https://ui-avatars.com/api/?name=Ghazy+Urbayani&background=3B82F6&color=fff',
};

export const mockStats = {
  topicsStudied: 5,
  mostTimeSpent: 'Data Mining',
  notesToFinish: 5,
};
